### PR TITLE
Update Collossus to work with google provider v2.0

### PR DESCRIPTION
**Pull request by smaslennikov**

### CODE REVIEW

**Comment by smaslennikov** [comment]
The following errors haunt us with google provider v2.0:

```
Error: module.network.module.nat.google_compute_instance_group_manager.primary: "auto_healing_policies": [REMOVED] This field is in beta. Use it in the the google-beta provider instead. See https://terraform.io/docs/providers/google/provider_versions.html for more details.

Error: module.network.module.nat.google_compute_instance_group_manager.primary: "auto_healing_policies.0.health_check": [REMOVED] This field is in beta. Use it in the the google-beta provider instead. See https://terraform.io/docs/providers/google/provider_versions.html for more details.

Error: module.network.module.nat.google_compute_instance_group_manager.primary: "auto_healing_policies.0.initial_delay_sec": [REMOVED] This field is in beta. Use it in the the google-beta provider instead. See https://terraform.io/docs/providers/google/provider_versions.html for more details.

Error: module.network.module.nat.google_compute_instance_group_manager.secondary: "auto_healing_policies": [REMOVED] This field is in beta. Use it in the the google-beta provider instead. See https://terraform.io/docs/providers/google/provider_versions.html for more details.

Error: module.network.module.nat.google_compute_instance_group_manager.secondary: "auto_healing_policies.0.health_check": [REMOVED] This field is in beta. Use it in the the google-beta provider instead. See https://terraform.io/docs/providers/google/provider_versions.html for more details.

Error: module.network.module.nat.google_compute_instance_group_manager.secondary: "auto_healing_policies.0.initial_delay_sec": [REMOVED] This field is in beta. Use it in the the google-beta provider instead. See https://terraform.io/docs/providers/google/provider_versions.html for more details.

Error: module.network.module.nat.google_compute_instance_template.primary: "network_interface.0.address": [REMOVED] Please use network_ip

Error: module.network.module.nat.google_compute_instance_template.secondary: "network_interface.0.address": [REMOVED] Please use network_ip
```

**Comment by smaslennikov** [comment]
We can either remove `auto_healing_policies` blocks or require `google-beta` provider. Fun.

Ideally we'd just replace this with the managed nat service.

**Comment by naftulikay** [comment]
:clap:

Thanks for submitting this. Since this would presumably break backwards compatibility with previous providers, it might make sense to push a new release to `modules/gcp/v0/2` with your patches.

Also, I'm still hoping to move Colossus to [naftulikay/colossus](https://github.com/naftulikay/colossus).

**Comment by naftulikay** [comment]
@smaslennikov Excellent. Have you tested that this does in fact build with the new provider? You might be able to use the `examples` to test building a network.

**Comment by smaslennikov** [comment]
@naftulikay more cleanup is to be done here; hold tight.

**Comment by smaslennikov** [comment]
@naftulikay this is now ready to go. I tested it with `google-beta v2.2` provider just now. Unfortunately, to keep the `auto_healing_policies`, we do have to require google-beta provider. Again, the proper alternative is to replace the whole module with the managed NAT. Sounds like work.

**Comment by smaslennikov** [comment]
@naftulikay oh, and I don't have write on the new Colossus repo - you do the migration when ready, or give me write access.

**Comment by naftulikay** [comment]
Generated diff between GCP 0.1 and 0.2:

<details>

<summary><code>git diff --no-index modules/gcp/v0/{1,2}</code></summary>

```diff
diff --git a/modules/gcp/v0/1/colossus_nat/instance_groups.tf b/modules/gcp/v0/2/colossus_nat/instance_groups.tf
index 32a6106..a3ebdc9 100644
--- a/modules/gcp/v0/1/colossus_nat/instance_groups.tf
+++ b/modules/gcp/v0/2/colossus_nat/instance_groups.tf
@@ -8,12 +8,14 @@ resource "google_compute_instance_group_manager" "primary" {
   description = "Colossus Primary NAT Gateway Instance Group in ${local.availability_zones[count.index]}."
   zone = "${local.availability_zones[count.index]}"
 
-  update_strategy = "RESTART"
   target_size = 1
 
   wait_for_instances = true
 
-  instance_template = "${element(google_compute_instance_template.primary.*.self_link, count.index)}"
+  version {
+    name = "nat-1"
+    instance_template = "${element(google_compute_instance_template.primary.*.self_link, count.index)}"
+  }
 
   named_port {
     name = "health-check"
@@ -34,12 +36,14 @@ resource "google_compute_instance_group_manager" "secondary" {
   description = "Colossus Secondary NAT Gateway Instance Group in ${local.availability_zones[count.index]}."
   zone = "${local.availability_zones[count.index]}"
 
-  update_strategy = "RESTART"
   target_size = 1
 
   wait_for_instances = true
 
-  instance_template = "${element(google_compute_instance_template.secondary.*.self_link, count.index)}"
+  version {
+    name = "nat-2"
+    instance_template = "${element(google_compute_instance_template.secondary.*.self_link, count.index)}"
+  }
 
   named_port {
     name = "health-check"
diff --git a/modules/gcp/v0/1/colossus_nat/instance_templates.tf b/modules/gcp/v0/2/colossus_nat/instance_templates.tf
index e1673a6..fbd2f33 100644
--- a/modules/gcp/v0/1/colossus_nat/instance_templates.tf
+++ b/modules/gcp/v0/2/colossus_nat/instance_templates.tf
@@ -27,7 +27,7 @@ resource "google_compute_instance_template" "primary" {
 
   network_interface {
     subnetwork = "${var.dmz_subnet_id}"
-    address = "${element(google_compute_address.private_primary.*.address, count.index)}"
+    network_ip = "${element(google_compute_address.private_primary.*.address, count.index)}"
     access_config {
       nat_ip = "${element(google_compute_address.public_primary.*.address, count.index)}"
     }
@@ -69,7 +69,7 @@ resource "google_compute_instance_template" "secondary" {
 
   network_interface {
     subnetwork = "${var.dmz_subnet_id}"
-    address = "${element(google_compute_address.private_secondary.*.address, count.index)}"
+    network_ip = "${element(google_compute_address.private_secondary.*.address, count.index)}"
     access_config {
       nat_ip = "${element(google_compute_address.public_secondary.*.address, count.index)}"
     }
diff --git a/modules/gcp/v0/1/colossus_network/main.tf b/modules/gcp/v0/2/colossus_network/main.tf
index c315a9e..67e0860 100644
--- a/modules/gcp/v0/1/colossus_network/main.tf
+++ b/modules/gcp/v0/2/colossus_network/main.tf
@@ -55,6 +55,7 @@ resource "google_dns_managed_zone" "public" {
   name = "${local.public_zone_name}"
   dns_name = "${local.zone}."
   description = "${local.public_zone_description}"
+  visibility = ""
 }
 
 resource "google_compute_route" "public" {
```

</details>

@smaslennikov can you give each `google_compute_instance_group_manager` for the NATs the same version name? [Docs here](https://www.terraform.io/docs/providers/google/r/compute_instance_group_manager.html#name-2).

Ideally, name them something like `nat-v0` or something.

Also, for the `google_dns_managed_zone` (the public one) can you change `visibility = ""` to `visibility = "public"` to make things explicit?

So:

 - Give each NAT `google_compute_instance_group_manager` the same `version.name`
 - Update the public `google_dns_managed_zone`'s `visibility` value to be `public`.

**Comment by smaslennikov** [comment]
@naftulikay the visibility part requires recreation, oddly:

```
-/+ module.network.google_dns_managed_zone.public (new resource required)
      id:             "public" => <computed> (forces new resource)
      description:    "Public Hosted Zone for the Colossus Stage Network." => "Public Hosted Zone for the Colossus Stage Network."
      dns_name:       "stage.pizza.com." => "stage.pizza.com."
      name:           "public" => "public"
      name_servers.#: "4" => <computed>
      project:        "pizza-stage" => <computed>
      visibility:     "" => "public" (forces new resource)
```

**Comment by smaslennikov** [comment]
these diffs are impossible

**Pull request merged**
