### PR TITLE
Fix license copyright

### PR DESCRIPTION
**Pull request by smaslennikov**

### CODE REVIEW

**Comment by naftulikay** [comment]
LOLAN that came from one of Herman's repos.

**Comment by smaslennikov** [comment]
The joke is that _I_ fixed this in his repos too! So maybe I was the culprit

**Comment by smaslennikov** [comment]
NOPE THIS IS YOUR COPYPASTA HAHA

**Comment by smaslennikov** [comment]
you mean i'll admin merge?

**Comment by naftulikay** [comment]
Enjoy not being a contributor anymore :wave:

**Comment by smaslennikov** [comment]
enjoy not having a contributor anymore

**Pull request merged**
