### PR TITLE
Update examples with new Colossus usage

### PR DESCRIPTION
**Pull request by smaslennikov**

### CODE REVIEW

**Comment by smaslennikov** [comment]
https://github.com/terraform-providers/terraform-provider-google/issues/3634 is a blocker for this to work.

**Comment by smaslennikov** [comment]
@naftulikay unsure what you mean by sandbox prefix. As per above issue, I'm able to validate the code while specifying region and project:

```
GOOGLE_REGION=us-central1 GOOGLE_PROJECT=myproject terraform plan
```

This works with `plan`, I haven't tried `apply`ing. Ready for merge, I suppose, and will fix https://github.com/naftulikay/titan/issues/62

**Comment by naftulikay** [comment]
the examples you modified are `examples/gcp/v0/1` and they're using the 0.3 modules. IDGAF either way.

**Comment by smaslennikov** [comment]
ah.
I guess I should fix that.

**Pull request merged**
