### PR TITLE
Fix travis validations

### PR DESCRIPTION
**Pull request by smaslennikov**
Fixes https://github.com/naftulikay/titan/issues/59 via https://www.terraform.io/docs/providers/aws/r/route53_zone.html#vpc_id

### CODE REVIEW

**Comment by smaslennikov** [comment]
https://www.terraform.io/docs/providers/aws/d/region.html is another mishap fixed here

**Comment by smaslennikov** [comment]
@naftulikay deprecations are fixed, but the titan tool fails to validate due to lack of credentials. According to some GH issue, adding `-backend=false` to `terraform init` would take care of this, but didn't. 

Fixing that tool is on you. Otherwise, this is ready.

**Comment by naftulikay** [comment]
@smaslennikov acknowledged. Since this is a change that could easily break things downstream, we need to integration test. We need an AWS account to test this against :disappointed: 

Once we have a proving ground, we'd need to :

 1. spin up an example using the old code from master.
 2. checkout this feature branch
 3. run a plan again and validate that nothing gets destroyed or broken

Unfortunately we don't have a good way to do this right now. 

I wish AWS had the 'project' notation that GCP has. If it did, I'd just create an account on every build and destroy _everything_ after Travis runs.

**Comment by smaslennikov** [comment]
This is a mess.

**Comment by naftulikay** [comment]
The documentation PR has fixes to Travis.

**Comment by naftulikay** [comment]
Superseded by #65.

**Pull request closed without merging**
